# Generated by Django 4.2.6 on 2024-03-05 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictec', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grado',
            options={'ordering': ['llama'], 'verbose_name': 'Grado', 'verbose_name_plural': 'Grados'},
        ),
        migrations.RenameField(
            model_name='grado',
            old_name='nombre',
            new_name='llama',
        ),
    ]
